import "./globals.css";

import OrderCode from "@/components/OrderCode";
import OrderingProvider from "./OrderingProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">

      <body className='bg-slate-50 flex flex-col justify-items-center m-3'>
        <OrderCode orderCode={''} />
        <OrderingProvider>
          {children}
        </OrderingProvider>
      </body>

    </html>
  );
}
